services:
  app:
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  proxy:
    image: proxy
    build:
      context: .
      dockerfile: Dockerfile.proxy
    ports:
      - "80:80"